services:
  backend-model:
    build: .
    ports:
      - "8024:8024"
    env_file:
      - .env  # Load the environment variables from the .env file
    networks:
      - govision-model-network

networks:
  govision-model-network:
    driver: bridge
