services:
  backend-model:
    build: .
    ports:
      - "8020:8020"
    env_file:
      - .env  # Load the environment variables from the .env file
    networks:
      - govision-network

networks:
  govision-network:
    driver: bridge
